- README.md
Users should not need `--release` for the example, since compilation time should dominate run time
Note that users should pick a back end
> Modify example-running command

- Cargo.toml
- src/lib.rs
- src/pipeline.rs
Fixes #7 and fixes #8.
This was quite a silly bug :sweat_smile: Basically, we were updating the old cache instead of the new one when a resize happened.
I have improved the internal API safety. Now, the `Cache` type does not leak outside `Pipeline`. Therefore, all mutations to it need to go through the `Cache` owner.
@rukai, let me know if the fix works for you!
> Fix cache resizes

- CHANGELOG.md
- examples/depth.rs
- examples/lipsum.txt
- src/builder.rs
- src/lib.rs
- src/pipeline.rs
> Depth testing support

- src/builder.rs
This makes it easier to write code for loading fonts into glyphbrush without needing to worry about which library is responsible for drawing them.
> Implement From<glyph_brush::GlyphBrushBuilder> for wgpu_glyph::GlyphBrushBuilder

- Cargo.toml
- src/lib.rs
Updates to the latest wgpu commit giving us access to the latest winit release.
Looks like glyph_brush requires getting texture_dimensions() from the built glyph_brush as initial_cache_size is no longer available. https://github.com/alexheretic/glyph-brush/blob/master/glyph-brush/CHANGELOG.md
> Update all dependencies

- examples/clipping.rs
- examples/depth.rs
- examples/hello.rs
- src/builder.rs
- src/lib.rs
In `wgpu` it seems like pipeline setup methods generally accept the `wgpu::Device` by immutable reference.  It works fine this way (`Pipeline::new` only requires an immutable reference), so I updated the API for creating a `GlyphBrush` to reflect that.
> Use immutable device ref when building GlyphBrush

- src/lib.rs
- src/pipeline.rs
None of the methods on wgpu::Device actually require a mutable reference, so all functions in wgpu_glyph should not require one either
> Don't require mutable reference to wgpu::Device

- Cargo.toml
The original semver specification `winit = "0.20.0-alpha4"` allows cargo to install `0.20.0`, which generates a bunch of errors:
```
error[E0599]: no method named `to_physical` found for type `winit::dpi::PhysicalSize<u32>` in the current scope
--> examples\hello.rs:33:40
|
33 |     let mut size = window.inner_size().to_physical(window.hidpi_factor());
|                                        ^^^^^^^^^^^ method not found in `winit::dpi::PhysicalSize<u32>`
error[E0599]: no method named `hidpi_factor` found for type `winit::window::Window` in the current scope
--> examples\hello.rs:33:59
|
33 |     let mut size = window.inner_size().to_physical(window.hidpi_factor());
|                                                           ^^^^^^^^^^^^ method not found in `winit::window::Window` …
```
> Force cargo to install winit-0.20.0-alpha4

- Cargo.toml
- examples/clipping.rs
- examples/depth.rs
- examples/hello.rs
- src/builder.rs
- src/lib.rs
- src/pipeline.rs
This PR updates `glyph_brush` to [the latest release](https://github.com/alexheretic/glyph-brush/releases/tag/glyph-brush-0.7).
These are the minimum changes to keep the examples working as before. There may be new API methods that we need to expose.
Let me know if you find anything amiss.
Fixes #42. Fixes #37.
> Update `glyph_brush` to `0.7`

- examples/clipping.rs
- examples/depth.rs
- examples/hello.rs
- src/lib.rs
- src/pipeline.rs
- src/pipeline/cache.rs
Instead of reallocating staging buffers every frame, we ask the user to provide a staging belt of buffers.
@rukai @dhardy Does this seem like a good idea to you?
> Use `StagingBelt` for uploading data

- CHANGELOG.md
- Cargo.toml
- src/pipeline.rs
Depends on #50.
Replaces `zerocopy` with `bytemuck`, which should reduce compilation time.
> Replace `zerocopy` with `bytemuck`

- Cargo.toml
Depends on #51.
Updates the `winit` dev-dependency to the latest release.
> Update `winit` to `0.24`

- src/builder.rs
glyph_brush switched from seahash to xxhash in 0.4.1 https://github.com/alexheretic/glyph-brush/blob/efd4f76923bdbcfe0929a1fa757bd60d5ee52db0/glyph-brush/CHANGELOG.md#041
See [here](https://github.com/alexheretic/glyph-brush/blob/75534d782002db4faf735405ecb4116fe96fdbe1/gfx-glyph/src/builder.rs#L120) for it's up to date documentation
> Fix stale section_hasher doc default hasher comment

- Cargo.toml
- src/pipeline.rs
- Update wgpu to 0.9 (no changes required)
- While at it, I replaced manually defined vertex attributes with wgpu built-in macro (if there was any reason for those to be manually defined then I can just drop the commit, just let me know)
> Update `wgpu` to `0.9`

- src/shader/glyph.wgsl
From the WGSL spec: "Each switch statement must have exactly one default clause."
Chrome/Tint emits the following error when compiling the shader:
```
Tint WGSL reader failure:
Parser: 35:5 error: switch statement must have a default clause
switch (i32(input.vertex_index)) {
^^^^^^
```
naga doesn't yet validate the presence of a default clause but should do so soonish via https://github.com/gfx-rs/naga/pull/1529.
> Add default branch to wgsl switch

- src/pipeline.rs
Followup to https://github.com/hecrj/wgpu_glyph/pull/79. See the commit messages for details. With these fixes wgpu_glyph works in Chrome Canary. :tada:
> Make wgpu_glyph work on Chrome

- src/builder.rs
- src/lib.rs
- src/pipeline.rs
This adds a function to the builder to allow setting the multisample
state. If it is not called, the default is used as before.
> Add support for passing a multisample state

- Cargo.toml
- examples/clipping.rs
- examples/depth.rs
- examples/hello.rs
- src/shader/glyph.wgsl
The wgpu update is useful for users of this crate, while the winit update is only relevant to the examples in this repo. I also touched up the WGSL code. If you prefer, I can remove the last commit.
This can be be reviewed commit by commit.
Changelogs: [wgpu](https://github.com/gfx-rs/wgpu/releases/tag/v0.19.0), [winit](https://github.com/rust-windowing/winit/releases/tag/v0.29.2)
---
Thanks for this crate btw. I know the README now says this has been superseeded by [glyphon](https://github.com/grovesNL/glyphon), but I still think there is a place for `wgpu_glyph`. At least for now. Switching to glyphon isn't straight forward if you are already using `wgpu_glyph` and cosmic-text still lacks some features like changing font size within one text block. So thanks for still maintaining this!
> Update wgpu to 0.19 and winit to 0.29

- Cargo.toml
- src/pipeline.rs
This upgrades the wgpu version from 0.19 to 23.
Only some minor changes were necessary.
Even though this crate is discontinued, it would be nice to be able to keep using it with recent versions of wgpu for projects that depend on it currently and don't want to move everything to glyphon yet.
> Upgrade wgpu to 23

- Cargo.toml
- examples/clipping.rs
- examples/depth.rs
- examples/hello.rs
- src/pipeline.rs
- src/pipeline/cache.rs
This upgrades the wgpu version from 23 to 26.
Only some minor changes were necessary.
Even though this crate is discontinued, it would be nice to be able to keep using it with recent versions of wgpu for projects that depend on it currently and don't want to move everything to glyphon yet.
> Upgrade wgpu to 26
